version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db_book
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    container_name: redis_book
    env_file:
      - .env
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: book
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
